# Main config file for generating the manual(S).
# Primarily will generate online gh-pages with more exhaustive documentation than the bog-standard API docs from e.g.
# go-doc.
# Hopefully can also be extended to offline/downloadable formats (HTML, ePub, man file, whatever.)

# Couple of variants for the header I quite like
site_name: '⧼Zelkata Manual⧽'
#site_name: '⦗Zelkata Manual⦘'
site_description: User manual for the Zelkata system.

site_url: https://zelkata.omnikron13.uk
site_author: Joey Sabey
copyright: Copyright &copy; 2024 Joey Sabey

# Link back to the repo that'll lurk in the top right corner
repo_url: https://github.com/omnikron13/zelkata/
repo_name: Zelkata Github repo

# Don't copy files used for building/generating the manual into the site
exclude_docs: |
  ./scripts/
  *.sass
  *.scss

# Only include drafts in serve, not in actual builds
draft_docs: |
  .draft.md

# Main navigation
nav:
   - 󰭷 Introduction: index.md
   - 󱚊 Specifications: specifications/index.md

# Leverage the impressive feature set of the material theme (though the actual theming needs some work...)
theme:
   name: material
   palette:
     scheme: catppuccin-macchiato
     #scheme: slate

   # Disable default font loading from Google fonts - we are going to be using patched Nerd Fonts for now
   fonts: none

extra_css:
   # Loading compiled version of the (WIP) Catppuccin theme.
   - assets/stylesheets/catppuccin-macchiato.compiled.css
   # Pulling in a patched Nerd Font for the icons, at least for now; I think you may be able to just map the symbols?
   - assets/fonts/default-font.css

extra_javascript:
   - assets/scripts/add_accents.js

# TODO: properly review what we may need
markdown_extensions:
 - admonition
 - pymdownx.details
 - pymdownx.superfences

plugins:
  - search
  - minify:
    minify_html: true
    minify_js: true
    minify_css: true
    htmlmin_opts:
        remove_comments: true
    cache_safe: true
    js_files:
        - assets/**/*.js
    #    - assets/javascript/*.ts
    #    - assets/javascript/*.tsx
    css_files:
        - assets/**/*.css

