name: Publish manual via GitHub Pages
on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    name: Deploy manual to pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            docs

      - name: Download & unpack Nerd Fonts
        env:
          font: Ubuntu
          version: v3.2.1
          destination: docs/assets/fonts/
        run: |
          wget "https://github.com/ryanoasis/nerd-fonts/releases/download/${version}/${font}.zip"
          unzip -j "${font}.zip" -d "${destination}/${font}"

      - name: Deploy pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml

